# Generated by Django 4.0.4 on 2022-05-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gallery_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.CharField(blank=True, choices=[('custom', 'custom'), ('event', 'event'), ('student', 'student')], default='custom', max_length=150, null=True),
        ),
    ]
